//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscription
    {
        public int Id { get; set; }
        public int StudentStudentId { get; set; }
        public int MatterMatterId { get; set; }
    
        public virtual Matter Matter { get; set; }
        public virtual Student Student { get; set; }
    }
}
