//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ModelFirts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matter
    {
        public int MatterId { get; set; }
        public string Name { get; set; }
        public int TeacherTeacherId { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
