// <auto-generated />
using System;
using CodeFirst.Two.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.Two.Migrations
{
    [DbContext(typeof(CodeFirstTwoContext))]
    [Migration("20190529194611_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst.Two.Models.Bath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<Guid?>("DogId");

                    b.Property<DateTime?>("LastUpdatedOn");

                    b.Property<float>("Price");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.ToTable("Baths");
                });

            modelBuilder.Entity("CodeFirst.Two.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FatherName")
                        .HasColumnType("NVARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastUpdatedOn");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Dogs","AEO");
                });

            modelBuilder.Entity("CodeFirst.Two.Models.Bath", b =>
                {
                    b.HasOne("CodeFirst.Two.Models.Dog", "Dog")
                        .WithMany()
                        .HasForeignKey("DogId");
                });
#pragma warning restore 612, 618
        }
    }
}
